// 国家代码到前端地图文件夹名称的映射
// 根据 frontend/src/data/maps 目录中的实际地图数据创建
export const countryCodeToMapFolder: Record<string, string> = {
  // 已有映射
  'CN': 'china',
  'US': 'usa',
  'JP': 'japan',
  'KR': 'south-korea',
  'FR': 'france.regions', // 法国有多个地图，使用 regions
  'DE': 'germany',
  'IT': 'italy',
  'ES': 'spain',
  'AU': 'australia',
  'CA': 'canada',
  'BR': 'brazil',
  'MX': 'mexico',
  'IN': 'india',
  
  // 补充其他有地图数据的国家
  'AT': 'austria',
  'KH': 'cambodia',
  'CM': 'cameroon',
  'CV': 'cape-verde',
  'CO': 'colombia',
  'DK': 'denmark',
  'GR': 'greece',
  'HN': 'honduras',
  'HK': 'hong-kong',
  'ID': 'indonesia',
  'IL': 'israel',
  'KE': 'kenya',
  'MD': 'moldova',
  'NL': 'netherlands',
  'NZ': 'new-zealand',
  'NG': 'nigeria',
  'PK': 'pakistan.districts', // 巴基斯坦使用 districts 地图
  'PR': 'puerto-rico',
  'RO': 'romania',
  'SA': 'saudi-arabia',
  'LK': 'sri-lanka',
  'SE': 'sweden',
  'TW': 'taiwan',
  'TZ': 'tanzania',
  'TH': 'thailand',
  'TN': 'tunisia',
  'AE': 'uae',
  'UA': 'ukraine',
  'UZ': 'uzbekistan',
  'VN': 'vietnam',
  'ZW': 'zimbabwe',
}

// Admin1 代码到地图ID的映射
// 用于数据库迁移和地图数据转换
export const admin1CodeToMapId: Record<string, string> = {
  // 中国省份
  'CN-BJ': 'beijing',
  'CN-SH': 'shanghai',
  'CN-TJ': 'tianjin',
  'CN-CQ': 'chongqing',
  'CN-HE': 'hebei',
  'CN-SX': 'shanxi',
  'CN-LN': 'liaoning',
  'CN-JL': 'jilin',
  'CN-HL': 'heilongjiang',
  'CN-JS': 'jiangsu',
  'CN-ZJ': 'zhejiang',
  'CN-AH': 'anhui',
  'CN-FJ': 'fujian',
  'CN-JX': 'jiangxi',
  'CN-SD': 'shandong',
  'CN-HA': 'henan',
  'CN-HB': 'hubei',
  'CN-HN': 'hunan',
  'CN-GD': 'guangdong',
  'CN-GX': 'guangxi-zhuang',
  'CN-HI': 'hainan',
  'CN-SC': 'sichuan',
  'CN-GZ': 'guizhou',
  'CN-YN': 'yunnan',
  'CN-SN': 'shaanxi',
  'CN-GS': 'gansu',
  'CN-QH': 'quinghai',
  'CN-TW': 'taiwan',
  'CN-NM': 'nei-mongol',
  'CN-XJ': 'xinjiang-uygur',
  'CN-XZ': 'xizang',
  'CN-NX': 'ningxia-hui',
  'CN-HK': 'hong-kong',
  'CN-MO': 'macau',
  
  // 美国州
  'US-AL': 'al', 'US-AK': 'ak', 'US-AZ': 'az', 'US-AR': 'ar',
  'US-CA': 'ca', 'US-CO': 'co', 'US-CT': 'ct', 'US-DE': 'de',
  'US-FL': 'fl', 'US-GA': 'ga', 'US-HI': 'hi', 'US-ID': 'id',
  'US-IL': 'il', 'US-IN': 'in', 'US-IA': 'ia', 'US-KS': 'ks',
  'US-KY': 'ky', 'US-LA': 'la', 'US-ME': 'me', 'US-MD': 'md',
  'US-MA': 'ma', 'US-MI': 'mi', 'US-MN': 'mn', 'US-MS': 'ms',
  'US-MO': 'mo', 'US-MT': 'mt', 'US-NE': 'ne', 'US-NV': 'nv',
  'US-NH': 'nh', 'US-NJ': 'nj', 'US-NM': 'nm', 'US-NY': 'ny',
  'US-NC': 'nc', 'US-ND': 'nd', 'US-OH': 'oh', 'US-OK': 'ok',
  'US-OR': 'or', 'US-PA': 'pa', 'US-RI': 'ri', 'US-SC': 'sc',
  'US-SD': 'sd', 'US-TN': 'tn', 'US-TX': 'tx', 'US-UT': 'ut',
  'US-VT': 'vt', 'US-VA': 'va', 'US-WA': 'wa', 'US-WV': 'wv',
  'US-WI': 'wi', 'US-WY': 'wy', 'US-DC': 'dc'
}

